_uri || null,
              _creator_uri_user || null,
              _creation_date :dataToSend._creation_date,
              _last_update_uri_user || null,
              _last_update_date || null,
              _model_version || null,
              _ui_version || null,
              _is_complete || null,
              _submission_date || null,
              _marked_as_complete_date || null,
              land_statistics_beat_land_bio_other_plant_ha ||
                null,
              guser_tloc_fd_beat_point_lng || null,
              fbli_fa_tloc_fd_beat || null,
              logistics3_countryboat_condition || null,
              logistics4_gfirearms_303rifle || null,
              land_statistics_beat_mgt_approach_other_pa_area_ha ||
                null,
              logistics4_others_water_tra || null,
              bo_info_bo_cell || null,
              logistics3_tvessel_condition || null,
              ro_info_ro_cell || null,
              logistics4_tfirearms_chineserifle_avail || null,
              logistics3_tvessel_avail || null,
              fbli_fa_tloc_fd_beat_txt || null,
              logistics3_speedboat_condition || null,
              fbli_fa_tloc_fd_division || null,
              land_transports_bicycle_avail || null,
              logistics3_others_water_tra_condition || null,
              land_statistics_beat_land_info_vested_forest_ha ||
                null,
              subscriberid || null,
              guser_user || null,
              ro_info_name_of_ro || null,
              fbli_fa_tloc_fd_block || null,
              deviceid || null,
              land_transports_motorb_condition || null,
              fbli_generated_note_name_18 || null,
              land_statistics_beat_land_bio_generated_note_name_74 ||
                null,
              logistics4_chineserifle_condition || null,
              logistics3_speedboat_avail || null,
              land_statistics_beat_mgt_approach_pa_ws_ha ||
                null,
              logistics4_generated_note_name_152 || null,
              land_statistics_beat_land_bio_non_pp_ha || null,
              land_statistics_beat_land_info_section_6_ha ||
                null,
              simserial || null,
              guser_dcollection_raw || null,
              land_transports_bicycle_condition || null,
              land_statistics_beat_land_bio_social_accreted_ha ||
                null,
              guser_generated_note_name_10 || null,
              land_statistics_beat_land_info_other_forestarea_ha ||
                null,
              bo_info_bo_nid || null,
              land_transports_gbi_cycle || null,
              land_transports_others_land_tra || null,
              logistics3_gcountry_boat || null,
              logistics4_gfirearms_slr || null,
              fbli_fa_tloc_fd_cir || null,
              land_transports_motorb_avail || null,
              land_transports_others_land_tra_condition ||
                null,
              ro_info_ro_joining_date || null,
              logistics4_others_water_tra_condition || null,
              land_statistics_beat_land_bio_natural_to_dc_ha ||
                null,
              ro_info_ro_rank || null,
              land_transports_others_land_tra_avail || null,
              land_statistics_beat_mgt_approach_pa_safaripark_ha ||
                null,
              bo_info_bo_joining_date || null,
              guser_user_cell || null,
              ro_info_ro_nid || null,
              guser_tloc_fd_beat_point_alt || null,
              land_statistics_beat_land_info_section_4_ha ||
                null,
              guser_tloc_fd_beat_point_lat || null,
              land_statistics_beat_mgt_approach_pa_sbca_ha ||
                null,
              logistics4_rifle303_condition || null,
              guser_dcollection || null,
              end_raw || null,
              bo_info_generated_note_name_106 || null,
              generated_note_name_81 || null,
              ro_info_generated_note_name_97 || null,
              fbli_fa_generated_note_name_21 || null,
              land_transports_generated_note_name_125 || null,
              guser_beat_address || null,
              land_statistics_beat_land_info_aquired_forest_ha ||
                null,
              bo_info_bo_joining_date_raw || null,
              land_statistics_beat_mgt_approach_pa_np_ha ||
                null,
              guser_tloc_fd_beat_point_acc || null,
              logistics3_countryboat_avail || null,
              fbli_ca_tloc_ad_district || null,
              bo_info_name_of_bo || null,
              land_statistics_beat_land_info_generated_note_name_53 ||
                null,
              land_statistics_beat_land_info_reserved_forest_ha ||
                null,
              logistics3_others_water_tra || null,
              fbli_tloc_ecozone || null,
              bo_info_bo_rank || null,
              logistics4_slr_condition || null,
              end || null,
              fbli_fa_tloc_fd_range || null,
              ro_info_ro_joining_date_raw || null,
              phonenumber || null,
              logistics3_trawler || null,
              logistics4_gfirearms_shortgun || null,
              logistics4_shortgun_condition || null,
              start_raw || null,
              land_statistics_total_legal_land_stats || null,
              bo_info_bo_mail || null,
              meta_instance_id || null,
              logistics4_tfirearms_shortgun_avail || null,
              fbli_ca_generated_note_name_33 || null,
              fbli_ca_tloc_ad_division || null,
              land_statistics_beat_mgt_approach_generated_note_name_65 ||
                null,
              logistics4_others_water_tra_avail || null,
              logistics3_gspeed_boat || null,
              logistics4_tfirearms_303rifle_avail || null,
              logistics4_gfirearms_chineserifle || null,
              today || null,
              fbli_fa_tloc_fd_char || null,
              land_transports_gmotorbike || null,
              land_statistics_beat_land_info_protected_forest_ha ||
                null,
              land_statistics_beat_mgt_approach_pa_ecopark_ha ||
                null,
              fbli_fa_tloc_enter_range || null,
              land_statistics_area_sum || null,
              ro_info_ro_mail || null,
              generated_note_name_123 || null,
              start || null,
              fbli_ca_union || null,
              fbli_fa_tloc_enter_div || null,
              today_raw || null,
              generated_note_name_94 || null,
              logistics3_others_water_tra_avail || null,
              generated_note_name_95 || null,
              logistics4_tfirearms_slr_avail || null,
              logistics3_generated_note_name_137 || null,
              project_id || null,
              sort || null,
              last_log_id || null,
              restore_id || null,
              created_at || null,
              created_by || null,
              updated_at || null,
              updated_by || null,
              deleted_at || null,
              deleted_by || null,
              deleted_status || null,
              status || null,
              land_statistics_beat_land_bio_social_accreted_skm ||
                null,
              land_statistics_beat_land_bio_non_pp_skm ||
                null,
              land_statistics_beat_land_bio_other_plant_skm ||
                null,